version: "3.7"
services:
  backend:
    image: "${DOCKER_IMAGE_BACKEND}:${TAG-latest}"
    ports:
      - "8000:8000"
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=http://${DOMAIN}
      - TAG=${TAG}
    volumes:
      - ./api/app:/app
    build:
      context: ./api
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 #/start-reload.sh
    networks:
      dev-network:
          ipv4_address: 172.29.0.4
          
  frontend:
    image: "${DOCKER_IMAGE_FRONTEND}:${TAG-latest}"
    ports:
      - "8080:8080"
    volumes:
      - ./spa:/app/
    build:
      context: ./spa
      args:
        FRONTEND_ENV: ${FRONTEND_ENV}
    command: npm run serve # -- --public 0.0.0.0:8080
    networks:
      dev-network:
          ipv4_address: 172.29.0.5

networks:
  dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.2/16
          gateway: 172.29.0.1