"""insert first user

Revision ID: 39e7d58b82e4
Revises: e4adec20835f
Create Date: 2023-09-09 11:57:19.635951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.security import get_password_hash

# revision identifiers, used by Alembic.
revision: str = '39e7d58b82e4'
down_revision: Union[str, None] = 'e4adec20835f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        INSERT INTO "user"(email, full_name, hashed_password, is_active, is_admin)
        VALUES ('admin@dev-web.com', 'ADMIN', '%s', TRUE, TRUE)
    """ % get_password_hash("devweb123"))

    op.execute("""
        INSERT INTO "address"(street, street_number, neighborhood, city, uf)
        VALUES ('Rua 1', 950, 'Centro', 'Camboriú', 'SC')
    """)

    op.execute("""
        INSERT INTO user_address(user_id, address_id)
        VALUES (1, 1)
    """)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
