"""update user_tool

Revision ID: 560409d10990
Revises: ebef64060f50
Create Date: 2023-09-10 12:19:11.218540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560409d10990'
down_revision: Union[str, None] = 'ebef64060f50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tool', sa.Column('allow_create', sa.Boolean(), nullable=True))
    op.add_column('user_tool', sa.Column('allow_read', sa.Boolean(), nullable=True))
    op.add_column('user_tool', sa.Column('allow_update', sa.Boolean(), nullable=True))
    op.add_column('user_tool', sa.Column('allow_delete', sa.Boolean(), nullable=True))

    op.execute("""
        UPDATE user_tool SET
               allow_create = TRUE,
               allow_read = TRUE,
               allow_update = TRUE,
               allow_delete = TRUE
        WHERE
            user_id = 1
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tool', 'allow_delete')
    op.drop_column('user_tool', 'allow_update')
    op.drop_column('user_tool', 'allow_read')
    op.drop_column('user_tool', 'allow_create')
    # ### end Alembic commands ###
