"""add icon on tool

Revision ID: 5745ae2b9fa6
Revises: 560409d10990
Create Date: 2023-09-10 14:57:08.968565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5745ae2b9fa6'
down_revision: Union[str, None] = '560409d10990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute("""UPDATE tool SET icon = 'mdi-account-group' WHERE id = 1""")
    op.alter_column("tool", "icon", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'icon')
    # ### end Alembic commands ###
