"""add users teste

Revision ID: 707f6226de9d
Revises: 5745ae2b9fa6
Create Date: 2023-09-14 19:34:45.531695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '707f6226de9d'
down_revision: Union[str, None] = '5745ae2b9fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        INSERT INTO public.address (created_at, updated_at, street, street_number, neighborhood, city, uf) VALUES('2023-09-14 19:38:49.365', '2023-09-14 19:38:49.365', 'Rua Marmeleiro', '54', 'Tabuleiro', 'Camboriú', 'SC');
        INSERT INTO public.address (created_at, updated_at, street, street_number, neighborhood, city, uf) VALUES('2023-09-14 19:38:49.369', '2023-09-14 19:38:49.369', 'Rua Francisco', '566', 'Centro', 'Camboriú', 'SC');
        INSERT INTO public.address (created_at, updated_at, street, street_number, neighborhood, city, uf) VALUES('2023-09-14 19:38:49.371', '2023-09-14 19:38:49.371', 'Rua Maria', '7', 'Centro', 'Balneário Camboriú', 'SC');
        INSERT INTO public.address (created_at, updated_at, street, street_number, neighborhood, city, uf) VALUES('2023-09-14 19:38:49.373', '2023-09-14 19:38:49.373', 'Rua Salvador', '125', 'Municípios', 'Camboriú', 'SC');
        INSERT INTO public.address (created_at, updated_at, street, street_number, neighborhood, city, uf) VALUES('2023-09-14 19:38:49.375', '2023-09-14 19:38:49.375', 'Rua Bahia', '128', 'Estados', 'Camboriú', 'SC');
    """)

    op.execute("""
        INSERT INTO public."user" (created_at, updated_at, email, full_name, hashed_password, is_active, is_admin) VALUES('2023-09-14 22:37:36.795', '2023-09-14 22:37:36.795', 'joao.francisco@dev-web.com', 'João Francisco', '$2bd$12$mbDr/HwahjkcXuaaU.ihueUO3O.1TthUGzOS7HowuxaUd3FTxVSGy', true, false);
        INSERT INTO public."user" (created_at, updated_at, email, full_name, hashed_password, is_active, is_admin) VALUES('2023-09-14 22:37:36.795', '2023-09-14 22:37:36.795', 'mariaantonieta@gmail.com', 'Maria Antonieta', '$2b$12$mbDr/HwahjkcXuaaU.ihueUO3O.1TthUGzOS7HowuxaUd3FTsxVSGy', true, false);
    """)

    op.execute("""
        INSERT INTO public.user_address (created_at, updated_at, user_id, address_id) VALUES('2023-09-14 22:37:36.795', '2023-09-14 22:37:36.795', 2, 2);
        INSERT INTO public.user_address (created_at, updated_at, user_id, address_id) VALUES('2023-09-14 22:37:36.795', '2023-09-14 22:37:36.795', 2, 3);
        INSERT INTO public.user_address (created_at, updated_at, user_id, address_id) VALUES('2023-09-14 22:37:36.795', '2023-09-14 22:37:36.795', 3, 4);
        INSERT INTO public.user_address (created_at, updated_at, user_id, address_id) VALUES('2023-09-14 22:37:36.795', '2023-09-14 22:37:36.795', 3, 5);
        INSERT INTO public.user_address (created_at, updated_at, user_id, address_id) VALUES('2023-09-14 22:37:36.795', '2023-09-14 22:37:36.795', 3, 6);
        INSERT INTO public.user_address (created_at, updated_at, user_id, address_id) VALUES('2023-09-14 22:37:36.795', '2023-09-14 22:37:36.795', 2, 6);
    """)

    op.execute("""
        INSERT INTO public.user_tool (created_at, updated_at, user_id, tool_id, allow_create, allow_read, allow_update, allow_delete) VALUES('2023-09-14 22:37:36.795', '2023-09-14 22:37:36.795', 2, 1, true, true, false, false);
        INSERT INTO public.user_tool (created_at, updated_at, user_id, tool_id, allow_create, allow_read, allow_update, allow_delete) VALUES('2023-09-14 22:37:36.795', '2023-09-14 22:37:36.795', 3, 1, false, false, true, true);
    """)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
