"""add tables tool and user_tool

Revision ID: ebef64060f50
Revises: 39e7d58b82e4
Create Date: 2023-09-10 12:15:34.124096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebef64060f50'
down_revision: Union[str, None] = '39e7d58b82e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool',
    sa.PrimaryKeyConstraint('id'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    )
    op.create_index(op.f('ix_tool_created_at'), 'tool', ['created_at'], unique=False)
    op.create_index(op.f('ix_tool_id'), 'tool', ['id'], unique=False)
    op.create_index(op.f('ix_tool_updated_at'), 'tool', ['updated_at'], unique=False)
    op.create_table('user_tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tool_created_at'), 'user_tool', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_tool_id'), 'user_tool', ['id'], unique=False)
    op.create_index(op.f('ix_user_tool_tool_id'), 'user_tool', ['tool_id'], unique=False)
    op.create_index(op.f('ix_user_tool_updated_at'), 'user_tool', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_tool_user_id'), 'user_tool', ['user_id'], unique=False)
    op.alter_column('address', 'street_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'neighborhood',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'uf',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


    op.execute("""
        INSERT INTO tool(name, path)
        VALUES ('Usuários', '/main/users')
    """)

    op.execute("""
        INSERT INTO user_tool(user_id, tool_id)
        VALUES(1, 1)
    """)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('address', 'uf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'neighborhood',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'street_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_user_tool_user_id'), table_name='user_tool')
    op.drop_index(op.f('ix_user_tool_updated_at'), table_name='user_tool')
    op.drop_index(op.f('ix_user_tool_tool_id'), table_name='user_tool')
    op.drop_index(op.f('ix_user_tool_id'), table_name='user_tool')
    op.drop_index(op.f('ix_user_tool_created_at'), table_name='user_tool')
    op.drop_table('user_tool')
    op.drop_index(op.f('ix_tool_updated_at'), table_name='tool')
    op.drop_index(op.f('ix_tool_id'), table_name='tool')
    op.drop_index(op.f('ix_tool_created_at'), table_name='tool')
    op.drop_table('tool')
    # ### end Alembic commands ###
